### ISSUE TITLE
Make it a single plugin

### ISSUE THREAD

**Issue by pinussilvestrus** [camunda/camunda-modeler-webpack-plugin#1]
__What should we do?__

Currently, there are two different plugins serving different use cases

* create a React extension
* create a Properties Panel extension

Considering possible other use cases that might pop up in the future, we should make this project offer _a single_ plugin that is configurable but still offers the same use cases.

I can imagine something like

```js
// webpack.config.js
const ModelerPlugin = require("camunda-modeler-webpack-plugins");

module.exports = {
  plugins: [
    new ModelerPlugin({
      type: 'react',
      loader: false,
      alias: true
    })
  ]
};
```

Cf. also to what plugin types we support: https://docs.camunda.io/docs/components/modeler/desktop-modeler/plugins/

__Why should we do it?__

Make things easiest as possible for our users to use. They shouldn't care which plugin to import.

**Comment by nikku** [comment]
Renamed already (`-s`).
